blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('answer/add', views.AnswerCreate.as_view(), name='answer_add'),
    path('answer/<uuid:pk>/', views.AnswerDetail.as_view(), name='answer_detail'),
    path('answer/<uuid:pk>/update/', views.AnswerUpdate.as_view(), name='answer_update'),
    path('answer/list/', views.AnswerListView.as_view(), name="answer_list"),
    path('procedury', views.procedury, name='procedury'),
    path('regulation', views.regulation, name='regulation'),
    path('consent', views.consent, name='consent'),
    path('documents', views.documents, name='documents')
]

curiosity/urls.py
from curiosity import views
from django.urls import path


app_name = "curiosity"

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/list/', views.PostListView.as_view(), name='post-list'),
    path('posts/create/', views.PostCreateView.as_view(), name='post-create'),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name="post-detail"),
    path('posts/<slug:slug>/update/', views.PostUpdateView.as_view(), name="post-change"),
    path('posts/<slug:slug>/delete/', views.PostDeleteView.as_view(), name="post-delete"),
]


urlpatterns += [
    path('authors/list/', views.PostAuthorListView.as_view(), name='author-list'),
    path('authors/create/', views.PostAuthorCreateView.as_view(), name='author-create'),
    path('authors/<pk>/', views.PostAuthorDetailView.as_view(), name="author-detail"),
    path('authors/<pk>/update/', views.PostAuthorUpdateView.as_view(), name="author-change"),
    path('authors/<pk>/delete/', views.PostAuthorDeleteView.as_view(), name="author-delete"),
]

urlpatterns += [
    path('tags/list/', views.TagListView.as_view(), name='tag-list'),
    path('tags/create/', views.TagCreateView.as_view(), name='tag-create'),
    path('tags/<pk>/', views.TagDetailView.as_view(), name="tag-detail"),
    path('tags/<pk>/update/', views.TagUpdateView.as_view(), name="tag-change"),
    path('tags/<pk>/delete/', views.TagDeleteView.as_view(), name="tag-delete"),

]

urlpatterns += [
    path('channels/list/', views.ChannelListView.as_view(), name='channel-list'),
    path('channels/create/', views.ChannelCreateView.as_view(), name='channel-create'),
    path('channels/<pk>/', views.ChannelDetailView.as_view(), name="channel-detail"),
    path('channels/<pk>/update/', views.ChannelUpdateView.as_view(), name="channel-change"),
    path('channels/<pk>/delete/', views.ChannelDeleteView.as_view(), name="channel-delete"),
]

urlpatterns += [
    path('posts/<slug:slug>/magic/', views.magic_publishe, name='post-magic'),
    path('posts/get/file/', views.get_new_posts_of_file, name='get_new_posts_of_file'),
    path('posts/get/net/', views.get_new_posts_of_network, name='get_new_posts_of_network'),
    path('authors/<pk>/posts/list/', views.PostByAuthorListView.as_view(), name="author-post-list"),
    path('channels/<id>/posts/list/', views.PostByChannelListView.as_view(), name="channel-posts"),
    path('tags/<pk>/posts/list/', views.PostByTagListView.as_view(), name="tag-posts"),
]

myblog/urls.py
# coding=utf-8
"""myblog URL Configuration

Список `urlpatterns` направляет URL-адреса к представлениям. Для получения дополнительной информации, пожалуйста, смотрите:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Примеры:
Функциональные представления
    1. Добавить импорт: из представлений импорта my_app
    2. Добавьте URL в urlpatterns:  path('', views.home, name='home')
Основанные на классе представления
    1. Добавить импорт: из other_app.views import Home
    2. Добавьте URL в urlpatterns:  path('', Home.as_view(), name='home')
Включая другой URLconf
    1. Импортируйте include() function: from django.urls import include, path
    2. Добавить URL-адрес в urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
import django.contrib.auth.urls
import curiosity.urls


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls, name="voooo"),
    path('', include('blog.urls')),
    path('curiosity/', include('curiosity.urls')),
]

curiosity/models.py
import os
import re
import uuid
import vk_api
import django
import requests
import platform
from django.db import models
from bs4 import BeautifulSoup
from django.urls import reverse
from django.utils import timezone
from urllib.parse import urlparse
from django.contrib.auth.models import User 
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from django.core.files.storage import FileSystemStorage


class Log(models.Model):
    text = models.TextField("Текст", max_length=5000, null=True)
    created_at = models.DateTimeField("Дата обнаружения", auto_now=False, default=django.utils.timezone.now, blank=True)

    def __str__(self):
        return self.text


class Channel(models.Model):
    name = models.CharField("Русское название", null=True, max_length=250, unique=True)
    name_en = models.CharField("Английское название", null=True, max_length=250, unique=True)
    created_date = models.DateTimeField("Даты создания", default=django.utils.timezone.now, blank=True)
    like = models.PositiveIntegerField("Лайк", default=0)

    def __str__(self):
        return self.name.capitalize()


class Tag(models.Model):
    name = models.CharField("Русское название", null=True, max_length=250, unique=True)
    name_en = models.CharField("Английское название", null=True, max_length=250, unique=True)
    created_date = models.DateTimeField("Даты создания", default=django.utils.timezone.now, blank=True)
    like = models.PositiveIntegerField("Лайк", default=0)

    def __str__(self):
        return self.name


class Image(models.Model):
    id = models.UUIDField("Интификатор", primary_key=True, default=uuid.uuid4(), editable=True)
    created_time = models.DateTimeField("Время создания", default=timezone.now)
    url_prefix = models.CharField("Префикс", max_length=len("https://dw8stlw9qt0iz.cloudfront.net/"), default="https://dw8stlw9qt0iz.cloudfront.net/")
    urls_x300 = models.TextField(verbose_name="Размеры x300", default=None, null=True)
    urls_x600 = models.TextField(verbose_name="Размеры x600", default=None, null=True)
    url_sufix = models.CharField("Суфикс", max_length=len(".png"), default=".png")

    ROLE = (
        ('о', 'Обложка'),
        ('б1', "Блок 1"),
        ('б2', "Блок 2"),
        ('б3', "Блок 3"),
    )

    role = models.CharField(
        "Позиция",
        max_length=2,
        choices=ROLE,
        blank=True,
        default='о',
    )

    class Meta:
        ordering = ['created_time']
        
        
    def nice_x300_url(self, size):
        path_list = self.urls_x300.split(', ')
        return self.url_prefix + path_list[size] + self.url_sufix
    
    
    def nice_x600_url(self, size):
        path_list = self.urls_x600.split(', ')
        return self.url_prefix + path_list[size] + self.url_sufix
    
    
    def get_storage(unix_pref, windows_pref):
        plat = platform.system()
        if plat == "Windows":
            return FileSystemStorage(location=os.path.join(windows_pref, "media"))
        elif plat != "Linux":
            return FileSystemStorage(location=os.path.join(unix_pref, "media"))
        else:
            return FileSystemStorage(location="")

    def get_path(self):
        pass
        #     if self.img:
        #         return mark_safe(str(self.img.path))
        #     else:
        #         return 'none'
        # display_img_path.short_description = 'Путь к изображению'
        # display_img_path.allow_tags = True

    def __str__(self):
        return str(self.id)


class PostAuthor(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Введите био подробности здесь.")
    
    class Meta:
        ordering = ["user","bio"]

    def get_absolute_url(self):
        """
        Возвращает URL для доступа конкретного экземпляра блог-автор.
        """
        return reverse('posts-by-author', args=[str(self.id)])

    def __str__(self):
        """
        Строка для представления объектной модели.
        """
        return self.user.username


class Post(models.Model):

    author = models.ForeignKey(PostAuthor, on_delete=models.SET_NULL, null=True, blank=True)
    comments = models
    title_en = models.CharField("Английский аголовок", max_length=500, unique=True, null=True)
    text_en = models.TextField("Английский текст", null=True)
    title = models.CharField("Заголовок", max_length=500, unique=True, null=True)
    html = models.TextField("ХТМЛ", null=True)
    url = models.URLField(verbose_name="Источник", null=True) 
    text = models.TextField("Русский текст", null=True)
    channel = models.ForeignKey(
        "Channel",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Рубрика"
        )
    tags = models.ManyToManyField(Tag, verbose_name="Хештеги")
    created_date = models.DateTimeField("Дата обнаружения", auto_now=False, default=django.utils.timezone.now, blank=True)
    pub_date = models.DateTimeField("Дата публикации", auto_now_add=True, null=True)
    rewrite_date = models.DateTimeField("Дата редактирования", null=True, auto_now=True,)
    slug = models.SlugField(max_length=255, null=True, unique=True)
    img = models.ForeignKey(
        Image,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Первое изображение"
        )
    FINDED = "Обнаружен"
    PUBLISHED = "Опубликован"
    STATUS = (
        (FINDED, "FINDED"),
        (PUBLISHED, "PUBLISHED"),
    )
    status = models.CharField(
        "Статус",
        max_length=15,
        choices=STATUS,
        null=False,
        default="Обнаружен"    
    )

    def get_absolute_url(self):
        return reverse("post-detail", args=[str(self.slug)])

    def parser(self):
        # НАСТРАИВАЕМ ПАРСЕРА
        r = requests.get(self.url)
        html = r.text.encode("utf-8")
        soup = BeautifulSoup(html, "lxml")
        page = soup.find("div", {"class": "topic-page"})
        content_header = page.find_all("div", {"class": "image-header"})
        contents = page.find("div", {"class": ["topic-content", "content-items"]})
        content_item = contents.find_all("div", {"class": "content-item"})
        regexp_img_1 = re.compile(r'https://dw8stlw9qt0iz\.cloudfront\.net/(.*?)\.png\"')
        text = soup.findAll(lambda tag: tag.name == 'div' and tag.get('class') == ['embedded-text-content'])
        t = text[:]
        texts = [text.p.text for text in t]
        text_1 = ""
        count = 0
        max_index = len(texts) - 1
        while count <= max_index:
            text_1 += texts[count] + '\n' + '\n'
            count += 1
        # Головные данные
        for item in content_header:
            # ТЕГИ ТЕКСТ
            try:
                if page.find("div", {"class", "topic-tags"}).text is not None:
                    tags = page.find("div", {"class", "topic-tags"}).text
            except AttributeError:
                tags = None
            # ID 1-го изображения
            img_1_href = re.findall(regexp_img_1, item.find('style').text)
            # ID видеоролика
            try:
                video_1_data_scr = \
                    contents.find("div", {"class": "first-video"}).find("div", {"class": "module-video"}).find("div", {
                        "class": "js-media-player"})["data-src"]
            except Exception as e:
                logger.exception(msg=f"Ошибка парсера: ссылка на видео не найдена - {e}")
                video_1_data_scr = None
            # условия прохода если HTML топика с багами
            if item.find("div", {"class": "header-content"}).find('a') != None:
                # название канала
                channel = item.find("div", {"class": "header-content"}).find('a').text
                # заголовок топика
                title = item.find("div", {"class": "header-content"}).find('h1').text
            elif item.find("div", {"class": "header-content"}).find('a') == None:
                channel = item.find("div", {"class": "header-content"}).find('h5').text
                title = item.find("div", {"class": "header-content"}).find('h1').text
        try:
            return img_1_href, channel, title, text_1, video_1_data_scr, tags, html
        except Exception as e:
            logger.exception(msg=f"Ошибка парсера: {e}")
            return img_1_href, channel, title, text_1, video_1_data_scr, tags, html

    def img_1_downloader(self, img_1_href, post_slug):
        if img_1_href is not None:
            img_url = "https://dw8stlw9qt0iz.cloudfront.net/" + img_1_href[35] + ".png"
            name = post_slug + ".png"
            res = requests.get("https://dw8stlw9qt0iz.cloudfront.net/" + img_1_href[35] + ".png", "b")
            with open(f"{os.getcwd()}/curiosity/static/curiosity/img/{post_slug}.png", 'wb') as zero:
                zero.write(res.content)
        else:
            print("Ошибка загрузки изображения")

    def draw(self, channel_ru, title_ru, img_path):
        img_path_resize = img_path + "_resize.png"
        img_path_draws = img_path + "_draws.png"
        # НАЗВАНИЕ КАНАЛА
        channel = channel_ru.upper()
        # ЗАГОЛОВОК
        if len(title_ru) <= 70:
            title = title_ru
        else:
            titlelist = list(title_ru)
            titlelist.insert(70, '-')
            titlelist.insert(71, '\n')
            title = ''.join(titlelist)
        # ОБЛОЖКА ТОПИКА НА АНГЛ.
        img_composit = Image.open(img_path).convert("RGBA")
        _size_im_composit = (2560, 2048)
        img_composit = img_composit.resize(_size_im_composit, resample=0)
        # БАЗА, ОНА ЖЕ - ЛОГО_ПАИНТЕР
        logo_painter = Image.open(PATH_TO_IMG_LOGO_PAINTER).convert("RGBA")
        # ШРИФТЫ
        channel_font = ImageFont.truetype(PATH_TO_FONTS, 64)
        title_font = ImageFont.truetype(PATH_TO_FONTS, 64)
        # РАЗМЕР БЛОКА ТЕКСТА С НАЗВАН
        channel_size = channel_font.getsize(str(channel))

curiosity/templates/curiosity/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Любопытство</title>{% endblock %}
  <meta name="description" content="Присоединяйтесь к миллионам людей, которые никогда не остановить обучения! Любопытство приносит вам в мире наиболее вдохновляющих статьи и видео, так что вы можете узнать что-то новое каждый день!">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!--Добавить дополнительный CSS в статическом файле -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'curiosity/css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'curiosity:index' %}">Домашняя</a></li>
        </ul>
           {% if user.is_authenticated %}
            <ul>
              <li>User: {{ user.get_username }}</li>
              <li><a href="{% url 'curiosity:author-post-list' user.id %}">Мои посты</a></li>
              {% if user.is_staff %}
                <li><a href="../../../admin/">Админка</a></li>
              {% endif %}
              <li><a href="{% url 'logout'%}?next={{request.path}}">Выйти</a></li>
            {% else %}
              <li><a href="{% url 'login'%}?next={{request.path}}">Авторизоваться</a></li>
             </ul>  
         {% endif %} 
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

curiosity/templates/curiosity/index.html
{% extends "curiosity/base_generic.html" %}

{% block title %}
<title>Любопытство - информация</title>
{% endblock%}

{% block content %}
  <h1>Это домашняя страница любопытства</h1>
  <p>Добро пожаловать, <em>Любопытство делает Вас умнее</em>!</p>
  <h2>Динамический контент</h2>
  <p>Этот блог имеет следующие записи счетчиков:</p>
  <ul>
    <li><strong>Доступно постов для публикации:</strong> {{ num_new }}</li>
    <li><strong>Постов опубликованно:</strong> {{ num_pub }}</li>
    <li><strong>Всего постов:</strong> {{ num_posts }}</li>
    <li><strong>Каналы:</strong> {{ num_channels }}</li>
    <li><strong>Тэги:</strong> {{ num_tags }}</li>
  </ul>
  <a href={% url 'curiosity:get_new_posts_of_file' %}>
    {% if user.is_superuser %}
      <button 
        class="btn btn-primary btn-lg"
        >Получить новые посты из файла
      </button>
    {% else %}
      <button 
        class="btn btn-primary btn-lg"
        disabled
        >Получить новые посты из файла
      </button>
    {% endif %}
  </a>
  <a href={% url 'curiosity:get_new_posts_of_network' %}>
    {% if user.is_superuser %}
      <button 
        class="btn btn-primary btn-lg"
        >Получить новые посты из интернета
      </button>
    {% else %}
      <button 
        class="btn btn-primary btn-lg"
        disabled
        >Получить новые посты из интернета
      </button>
    {% endif %}
  </a>
  <p id="num_visits">Вы посетили эту страницу {{num_visits}}{% if num_visits <= 1 %} раз{% else %} раза{% endif %}.</p>
{% endblock %}

curiosity/templates/curiosity/post_detail.html
{% extends 'curiosity/base_generic.html' %}

{% block content %}
    {% if post.pk %}
        <p>{{ post.title }}}</p>
    {% else %}
        <p>Ошибка в названии переменной</p>
    {% endif %}
{% endblock %}

curiosity/templates/curiosity/pubpost_list_author_user.html
{% extends 'curiosity/base_generic.html' %}

{% block content %}

<h1>Опубликованные посты</h1>

{% if post_list %}
<ul>
    {% for post in post_list %}
        <li class="{% if post.is_readypub %}text-danger {% endif %}">
            <a href="{% url 'curiosity:post-detail' post.slug %}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>
{% else %}
<p>У Вас не опубликованных постов</p>
{% endif %}

{% endblock  %}