blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('answer/add', views.AnswerCreate.as_view(), name='answer_add'),
    path('answer/<uuid:pk>/', views.AnswerDetail.as_view(), name='answer_detail'),
    path('answer/<uuid:pk>/update/', views.AnswerUpdate.as_view(), name='answer_update'),
    path('answer/list/', views.AnswerListView.as_view(), name="answer_list"),
    path('procedury', views.procedury, name='procedury'),
    path('regulation', views.regulation, name='regulation'),
    path('consent', views.consent, name='consent'),
    path('documents', views.documents, name='documents')
]

myblog/urls.py
# coding=utf-8
"""myblog URL Configuration

Список `urlpatterns` направляет URL-адреса к представлениям. Для получения дополнительной информации, пожалуйста, смотрите:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Примеры:
Функциональные представления
    1. Добавить импорт: из представлений импорта my_app
    2. Добавьте URL в urlpatterns:  path('', views.home, name='home')
Основанные на классе представления
    1. Добавить импорт: из other_app.views import Home
    2. Добавьте URL в urlpatterns:  path('', Home.as_view(), name='home')
Включая другой URLconf
    1. Импортируйте include() function: from django.urls import include, path
    2. Добавить URL-адрес в urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
import django.contrib.auth.urls
import curiosity.urls


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls, name="voooo"),
    path('', include('blog.urls')),
    path('curiosity/', include('curiosity.urls')),
]

blog/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils import timezone as timezone
from django.utils.translation import gettext as _
from multiselectfield import MultiSelectField
from phonenumber_field.modelfields import PhoneNumberField


KOMU_CHOICES = (
    ('Банкам', _('Банкам')),
    ('Часным', _('Часным лица')),
    ('Приставам', _('Судебным приставам')),
    ('Микрофинансам', _('Микрофинансовым организациям')),
    ('Другое', _('Другое')),
)
SKOLKO_CHOICES = (
    (1, 'До 200 000 руб'),
    (2, 'От 200 000 руб до 500 000 руб'),
    (3, 'От 500 000 руб до 1 000 000 руб'),
    (4, 'Более 1 000 000 руб'),
    (5, 'Более 5 000 000 руб'),
)
PROSROCHKY_CHOICES = (
    (1, 'Нет'),
    (2, 'Да, до месяца'),
    (1, 'Да, от месяца до трёх'),
    (1, 'Более трёх месяцев'),
)
ZALOGI_CHOICES = (
    (1, 'Есть'),
    (2, 'Нет')
)


class Client(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    ip = models.CharField(max_length=500)
    request_time = models.DateTimeField(default=timezone.now)

    def write(self):
        self.save()

    def __str__(self):
        return self.ip, self.request_time


class Answer(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    author = models.CharField(max_length=2000)

    created_time = models.DateTimeField(default=timezone.now)

    komu = MultiSelectField(
        "Кому Вы должны ?", choices=KOMU_CHOICES, max_choices=5,
        blank=False, help_text="Выберете 1 или более вариантов.", 
        error_messages={
            'invalid_list': 'Введите список значений.',
            'required': 'Обязательное поле.'
            })
    
    skolko = MultiSelectField(
        'Сколько всего Вы должны ?',
        choices=SKOLKO_CHOICES,
        max_choices=1,
        blank=False,
        help_text=f"Укажите пожалуйста приблизительный диапазон",
        error_messages={
            'required': 'Обязательное поле.'
            }
        )
    
    prosrochky = MultiSelectField(
        'Есть ли у Вас просрочки по кредитам ?',
        choices=PROSROCHKY_CHOICES,
        max_choices=1,
        blank=False,
        help_text=f"Или любым другим платежам срок по которым уже наступил.",
        error_messages={
            'required': 'Обязательное поле.'
            }
        )
    
    zalogi = MultiSelectField(
        'Есть ли у Вас имущество в залоге ?',
        choices=ZALOGI_CHOICES,
        max_choices=1,
        blank=False,
        help_text=f"Например, ипотечная квартира или \
            автомобиль купленный в автокредит.",
        error_messages={
            'required': 'Обязательное поле.'
            }
        )
    
    name = models.CharField(
        "Как Вас зовут ?",
        blank=False,
        max_length=200,
        default="",
        help_text=f"Представьтесь пожалуйста, \
             нам необходимо знать Ваше имя или псевдоним",
        error_messages={
            'required': 'Обязательное поле.'
            }
        )
    
    phone = PhoneNumberField(
        "Вот и последний шаг.",
        blank=False,
        unique=False,
        help_text=f"Введите Ваш номер телефона",
        error_messages={
            'required': 'Обязательное поле.'
            }
        )


    class Meta:
        ordering = ["-created_time"]
        

    def get_absolute_url(self):
        return reverse("blog:answer_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"""
        Дата: {self.created_time}
        IP автора: {self.author},
        Телефон: {self.phone},
        Имя: {self.name},
        Сколько: {self.skolko},
        Кому: {self.komu},
        Залоги: {self.zalogi}
        """

    def __unicode__(self):
        return self.__str__()


class Question(models.Model):
    
    question_text = models.CharField("Текст вопроса", max_length=200)
    pub_date = models.DateTimeField('date_published', null=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms
from .models import Answer
from phonenumber_field.formfields import PhoneNumberField


class AnswerForm(forms.ModelForm):
    phone = PhoneNumberField

    class Meta:

        model = Answer
        fields = (
            'skolko',
            'komu',
            'prosrochky',
            'zalogi',
            'name',
            'phone',
        )

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Client, Answer, Choice, Question
from django.utils import timezone
from blog.forms import AnswerForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ( 
    CreateView, UpdateView,
    ListView, DetailView
    )


class AnswerDetail(DetailView):
    model = Answer
    template_name = 'blog/answer_detail.html'


class AnswerCreate(CreateView):
    model = Answer
    fields = [
        "skolko",
        "komu",
        "prosrochky",
        "zalogi",
        "name",
        "phone"
        ]
    
    def form_valid(self, form):
        form.instance.author = get_client_ip(request=self.request)[0]
        return super().form_valid(form)


class AnswerUpdate(UpdateView):
    model = Answer
    fields = [
        "skolko",
        "komu",
        "prosrochky",
        "zalogi",
        "name",
        "phone"
        ]
    
    def form_valid(self, form):
        form.instance.author = get_client_ip(request=self.request)[0]
        return super().form_valid(form)


class AnswerListView(ListView):
    model = Answer
    context_object_name = 'answer_list'
    template_name = 'blog/answer_list.html'

    def get_queryset(self):
        """Return the last five published questions."""
        queryset = Answer.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AnswerListView, self).get_context_data(**kwargs)
        return context


def landing_page(request):
    ip, req_time = get_client_ip(request)
    return render(
        request,
        'blog/landing_page.html',
        { 
         'ip': ip,
         'req_time': req_time,
        }
    )

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    request_time = timezone.now()
    if x_forwarded_for:
        client_ip = x_forwarded_for.split(',')[-1]
        Client.objects.create(ip=client_ip, request_time=request_time)
    else:
        client_ip = request.META.get('REMOTE_ADDR')
        Client.objects.create(ip=client_ip, request_time=request_time)
    return client_ip, request_time

def procedury(request):
    return render(request, 'blog/procedury.html')

def regulation(request):
    return render(request, 'blog/regulation.html')

def consent(request):
    return render(request, 'blog/consent.html')

def documents(request):
    return render(request, 'blog/documents.html')

blog/templates/blog/answer_detail.html
{% extends 'blog/base.html' %}

{% block content %}

  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand"><a href="/">StepChange</a></h3>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link disabled" href="#">Позвоните нам: 8-800-808-08-80</a>
      </nav>
    </div>
  </header>

      <main role="main" id="main-detail" class="inner cover">
        <h1 class="cover-heading">Благодарим за ваши ответы.</h1>
        <p class="lead"> Номер вашей заявки: {{ answer.id }} </p>
        <p class="lead"> Наши специалисты незамедлительно с вами свяжутся.</p>
        <p class="lead">
          <a href="{% url 'blog:answer_update' answer.pk %}" class="btn btn-lg btn-secondary">Изменить ответы</a>
        </p>

      </main>
<footer class="mastfoot mt-auto">
        <div class="inner">
        <p>Раскрытие иформации о нашей <a href="https://sites.google.com/view/bankrotstvo/процедуры">Работе</a>, by <a href="https://twitter.com/MasterInManage">@kdo</a>.</p>
        </div>
    </footer>
{% endblock %}

blog/templates/blog/answer_form.html
{% extends 'blog/base.html' %}

{% block content %}

<main role="main" class="inner cover">
    <form id="form" class="needs-validation" method="POST" novalidate>
        {% csrf_token %}
        <div id="carouselExampleCaptions" class="carousel slide" data-cycle="false" data-interval="false">
            <div class="carousel-inner">
            {% for field in form %}
                {% if forloop.counter == 1 %}
                    <div class="carousel-item active">
                {% else %}
                    <div class="carousel-item">
                {% endif %}
                    <div id={{ field.name }} class="inner cover">
                        <nav class="nav">
                            <ul class="nav justify-content-left">
                                <li class="nav-item">
                                {% if field.name == 'skolko' %}
                                    <p class="lead">
                                    <a class="nav-link active" href="/" role="button">
                                        <button type="button" class="btn btn-secondary btn-sm">На главную</button>
                                    </a>
                                    </p>
                                {% else %}
                                    <a class="nav-link active" href="#carouselExampleCaptions" role="button" data-slide="prev">
                                        <button type="button" class="btn btn-secondary btn-sm">Назад</button>
                                    </a>
                                {% endif %}
                                </li>
                            </ul>
                        </nav>
                        <h2 class="lead">Шаг {{forloop.counter}}/{{form.fields|length}}</h2>
                        <p class="lead">
                            <h1 class="cover-heading">{{field.field.label}}</h1>
                            <h5 class="form-text text-muted">{{ field.help_text }}</h5>
                            <br/>
                            <table align="center" class="lead" id={{field.auto_id}}>
                                {% for choice in field.field.choices %}
                                <tr align="center" class="lead">
                                    <td class="lead">
                                            {% if field.name == 'komu' %}
                                                <div class="custom-control custom-checkbox" required>
                                                    <input type="checkbox" class="custom-control-input" name={{field.name}} value={{choice.0}} id={{field.auto_id}}_{{ forloop.counter }}>
                                                    <label class="custom-control-label" for="{{field.auto_id}}_{{ forloop.counter }}"> {{choice.1}}</label>
                                                </div>
                                            {% else %}
                                                <div class="custom-control custom-radio">
                                                    <input class="custom-control-input" type="radio" name={{field.name}} value={{choice.0}} id={{field.auto_id}}_{{ forloop.counter }} required>
                                                    <label class="custom-control-label" for="{{field.auto_id}}_{{ forloop.counter }}"> {{choice.1}}</label>
                                                </div>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                {% if field.name == 'name' %}
                                    <tr align="center" class="lead">
                                        <td class="lead">
                                            <input class="form-control" type="text" name="name" id="id_name_input" maxlength="200" placeholder="Данила" required>
                                        </td>
                                    </tr>
                                {% elif field.name == 'phone' %}
                                    <tr align="center" class="lead">
                                        <td class="lead">
                                            <input class="form-control" type="tel" name="phone" id="id_phone" placeholder="+79214447344" required>
                                            <div class="invalid-feedback">
                                                Без этого, к сожалению, мы не сможем рассчитать стоимость...
                                            </div>
                                        </td>
                                    </tr>
                                {% endif %}
                            </table>
                            <br>
                        </p>    
                    </div>
                    {% if field.name == 'phone' %}
                        <div>
                            <button id="send-form-btn" class="btn btn-secondary btn-lg" type="submit" disabled="true">Сохранить</button>
                        </div>
                    {% else %}
                            <span id="{{ field.name }}-next-popover"
                            data-container="body" data-toggle="popover" data-placement="top"
                            data-content="Для перехода к следующему шагу, необходимо ответить на этот вопрос"
                            >
                                <button
                                    type="button"
                                    href="#carouselExampleCaptions"
                                    style="pointer-events: none;"
                                    data-slide="next"
                                    id="next-{{ field.name }}-btn"
                                    class="btn btn-secondary btn-lg" 
                                    disabled
                                    >
                                    Дальше
                                </button>
                            </span>
                    {% endif %}
                </div>

                <!-- Добавить в отображение текущей формы -->
            <div id='alert' style="display: none" class="alert alert-dark" role="alert">
                Ответ на данный вопрос обезателен для определения стоимости банкротства !
              Если вы затрудняетесь ответить - воспользуйтесь нашим бесплатным сервисом проверки долгов !
                <button id="alert-close-btn" type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

<footer class="mastfoot mt-auto">
    <div class="inner">
    <p>Заполняя формы вы принимаете<a href="/regulation"> Положение</a> о конфидециальности и <a href="https://twitter.com/MasterInManage">Согласие</a> на обработку персональных данных</p>
    </div>
</footer>

{% load staticfiles %}
<script type="text/javascript" src="{% static 'blog/js/form.js' %}"></script>
{% endblock %}

blog/templates/blog/answer_list.html
{% extends 'blog/base.html' %}

{% block content %}

{% if answer_list %}
    <ul>
    {% for answer in answer_list %}
        <li><a href="{% url 'blog:answer-result' answer.pk %}">{{ answer }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

blog/templates/blog/answer_result.html
{% extends 'blog/base.html' %}

{% block content %}

  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">Банкрот</h3>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="/">Главная</a>
        <a class="nav-link" href="/procedury">Процедуры</a>
        <a class="nav-link" href="#">Контакты</a>
      </nav>
    </div>
  </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Благодарим за ваши ответы.</h1>
        <p class="lead"> Номер вашей заявки: {{ answer.id }} </p>
        <p class="lead"> Наши специалисты незамедлительно с вами свяжутся.</p>
        <p class="lead">
          <a href="{% url 'blog:answer-update' answer.pk %}" class="btn btn-lg btn-secondary">Изменить ответы</a>
        </p>

      </main>
<footer class="mastfoot mt-auto">
        <div class="inner">
        <p>Раскрытие иформации о нашей <a href="https://sites.google.com/view/bankrotstvo/процедуры">Работе</a>, by <a href="https://twitter.com/MasterInManage">@kdo</a>.</p>
        </div>
    </footer>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}

<form id="form" method="POST">
  {% csrf_token %}


<main id="komu" role="main" class="lead">
      <p class="lead"><label><h1 class="cover-heading">

      Кому Вы должны ?</h1></label><br/>


        <table align="center" class="lead" id="id_komu">
          <tr align="center" class="lead"><td class="lead">

            <label class="lead" for="id_komu_0">
                  <input type="checkbox" name="komu" value="Банкам" id="id_komu_0"
                  > Банкам
                </label>
          </td>
        </tr>
        <tr align="center" class="lead">
          <td>
              <label class="lead" for="id_komu_1">
                  <input type="checkbox" name="komu" value="Часным лица" id="id_komu_1"
                  > Часным лицам
                </label>
          </td>
        </tr>
        <tr align="center" class="lead">
          <td>
            <label class="lead" for="id_komu_2">
              <input type="checkbox" name="komu" value="Судебным приставам" id="id_komu_2"
              > Судебным приставам
            </label>
          </td>
        </tr>
        <tr align="center" class="lead">
          <td>
            <label class="lead" for="id_komu_3"><input type="checkbox" name="komu" value="Микрофинансовым организациям"
                id="id_komu_3"
                > Микрофинансовым организациям
            </label>
          </td>
        </tr>
        <tr align="center" class="lead">
          <td>
              <label class="lead" for="id_komu_4">
                  <input type="checkbox" name="komu" value="Другое" id="id_komu_4"
                  > Другое
              </label>
          </td>
        </tr>
      </table>
      <br>
      <p class="lead">
          <button id="komu-btn" disabled=true class="btn btn-lg btn-secondary"><div id="errorMessage">Дальше</div></button>
        </p>
      </p>
</main>
<!-- max stack render call fix -->
  <main id="skolko" role="main" class="lead" style="display: none">
    <p class="lead">
      <label><h1 class="cover-heading">Сколько всего Вы должны ?</h1></label><br/>
      <table align="center" class="lead" id="id_skolko">
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_skolko_0">
            <input type="radio" name="skolko" value="1" id="id_skolko_0"> До 200 000 руб
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_skolko_1">
            <input type="radio" name="skolko" value="2" id="id_skolko_1"> От 200 000 руб до 500 000 руб
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_skolko_2">
            <input type="radio" name="skolko" value="3" id="id_skolko_2"> От 500 000 руб до 1 000 000 руб
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_skolko_3">
            <input type="radio" name="skolko" value="4" id="id_skolko_3"> Более 1 000 000 руб
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_skolko_4">
            <input type="radio" name="skolko" value="5" id="id_skolko_4"> Более 5 000 000 руб
          </label>
        </td></tr>
      </table>
      <br/><p class="lead"><button id="skolko-btn" disabled=true class="btn btn-lg btn-secondary">Дальше</button>
    </p>
      </p>
  </main>



  <div id="prosrochky" style="display: none">
    <p>
      <label><h1 class="cover-heading">Есть ли у Вас просрочки по кредитам ?</h1></label><br/>

      <table align="center" class="lead" id="id_prosrochky">
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_prosrochky_0">
            <input type="radio" name="prosrochky" value="1" id="id_prosrochky_0">Нет
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_prosrochky_1">
            <input type="radio" name="prosrochky" value="2" id="id_prosrochky_1"> Да, до месяца
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_prosrochky_2">
            <input type="radio" name="prosrochky" value="1" id="id_prosrochky_2"> Да, от месяца до трёх
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_prosrochky_3">
            <input type="radio" name="prosrochky" value="1" id="id_prosrochky_3">Более трёх месяцев
          </label>
        </td></tr>
      </table>
      <br/><button id="prosrochky-btn" disabled=true class="btn btn-lg btn-secondary">Дальше</button>
    </p></p>
  </div>
<!-- Вопросительный знак -->
  <div id="zalogi" style="display: none">
    <p>
      <label><h1 class="cover-heading">Есть ли у Вас имущество в залоге ?</h1></label>
      <p class="lead">Например, ипотечная квартира или автомобиль купленный в
          автокредит.</p>
      <br/>
      <table align="center" class="lead" id="id_zalogi">
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_zalogi_0">
            <input type="radio" name="zalogi" value="1" id="id_zalogi_0">Есть
          </label>
        </td></tr>
        <tr align="center" class="lead"><td class="lead">
          <label class="lead" for="id_zalogi_1">
            <input type="radio" name="zalogi" value="2" id="id_zalogi_1">Нет
          </label>
        </td></tr>
      </table>
      <br/><button id="zalogi-btn" disabled=true class="btn btn-lg btn-secondary">Дальше</button>
    </p></p>
  </div>

  <div id="name" style="display: none">
    <p class="lead">
      <label class="lead" for="id_name"><h1 class="cover-heading">Как Вас зовут ?</h1></label>
      <input type="text" name="name" maxlength="200">
    </p>
    <br/><p class="lead">
        <button id="name-btn" class="btn btn-lg btn-secondary">Дальше</button>
    </p>
  </div>
<!-- Сделать правильную обработку ошибки ввода формы -->
  <div id="phone" style="display: none">
    <p class="lead">
      <label class="lead" for="id_phone"><h1 class="cover-heading">Телефон</h1></label>
      <input type="tel" name="phone" required id="id_phone">
      <br/>
     </p>
     <p class="lead"><br/><button id="send-form-btn" type="submit" class="btn btn-lg btn-secondary">Сохранить</button>
    </p>
  </div>

</form>
<!-- Добавить в отображение текущей формы -->
<div id='alert' style="display: none" class="alert alert-dark" role="alert">
    Ответ на данный вопрос обезателен для определения стоимости банкротства ! \n
    Если вы затрудняетесь ответить - воспользуйтесь нашим бесплатным сервисом проверки долгов !
    <button id="alert-close-btn" type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
{% load staticfiles %}
<script type="text/javascript" src="{% static 'blog/js/form.js' %}"></script>
{% endblock %}

blog/templates/blog/documents.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Процедуры</title>
<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
          <script src="{% static 'static_jquery/js/jquery.js' %}"></script>
</head>
<body>
  <ul class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
        <li>
        <a class="navbar-brand" href="/">Вернутся на сайт</a>
        </li>
  </ul>
    <!-- Place this tag where you want the Awesome Table Widget to render -->
<div data-type="AwesomeTableView" data-viewID="-LEivOWpD77ATwJGQIcm"></div>

<!-- Place this within the <head> tag or just before the end of your <body> tag. -->
<script src="https://awesome-table.com/AwesomeTableInclude.js"></script>

        <script src="{% static 'static_jquery/js/jquery.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/landing_page.html
{% extends 'blog/base.html' %}

{% block content %}
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">StepChange</h3>
      <nav class="nav nav-masthead justify-content-end">
        <a class="nav-link disabled" href="#">Позвоните нам: 8-800-808-08-80</a>
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Узнайте цену банкротства.</h1>
    <p class="lead">Пройдите короткий тест. Узнайте стоимость юридического сопровождения. Загружайте документы для подготовки заявления в электронном виде - получите скидку от 30% до 50%</p>
    <p class="lead">
      <a href="{% url 'blog:answer_add' %}" class="btn btn-lg btn-secondary">Пройти тест</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
        <div class="inner">
        <p>Раскрытие иформации о нашей <a href="https://sites.google.com/view/bankrotstvo/">Работе</a>,  power by <a href="https://twitter.com/MasterInManage">@kdo</a>.</p>
        </div>
    </footer>
{% endblock %}

blog/templates/blog/list.html
{% extends 'blog/base.html' %}

{% block content %}

{% if answer_list %}
    <ul>
    {% for answer in answer_list %}
        <li><a>{{ answer }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

blog/templates/blog/question_list.html
{% for question in latest_question_list  %}
    <h1><a>{{ question }}</a></h1>
{% endfor %}

blog/templates/blog/results.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'blog:detail' question.id %}">Vote again?</a>
{% endblock %}